# Generated by Django 3.1.7 on 2021-03-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('stars_number', models.IntegerField()),
                ('url', models.CharField(max_length=150)),
                ('merged_prs', models.TextField()),
                ('not_merged_prs', models.TextField()),
                ('user', models.CharField(max_length=50)),
            ],
        ),
    ]
