# Generated by Django 3.1.7 on 2021-03-19 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='check',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
