# Generated by Django 3.1.7 on 2021-03-23 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20210319_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Check',
            new_name='GithubProject',
        ),
    ]
